n=input(' Escreva qualquer coisa: ')
print('O tipo Primitivo é:', type(n))
print('Só tem espaços? ', n.isspace())
print('É um Número? ', n.isnumeric())
print('É alfabetico? ', n.isalpha())
print('É alfanumérico', n.isalnum())
print('Está em maiusculas? ', n.isupper())
print('Está em Minusculas? ', n.islower())
print('Está Capitalizada? ', n.istitle())